[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "guardian"
version = "0.1.0"
description = "Guardian Project"
authors = [
  { name="SpudrankX", email="your-email@example.com" }
]
dependencies = []
