name: Guardian CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest black flake8 isort

      - name: Check formatting with black
        run: black --check .

      - name: Check imports with isort
        run: isort . --check-only

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests
        run: pytest -v
